apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongo_eventstore
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: localhost:27017
  - name: databaseName
    value: dapr
  - name: collectionName
    value: dapr_humidity_eventstore
